### ISSUE TITLE
Rank images

### ISSUE THREAD

**Issue by DeinFreund** [Spring-Chobby/Chobby#225]
The current ones look blurry and ranks 5-8 are hard to differentiate. While I'm not really good at painting better ones, I would like to suggest to use color to indicate ELO and shape to indicate XP. 

Something along the lines of this maybe? (Rank 8 has multiple shades for demonstration of how that'd look)
https://i.imgur.com/Q5tTO03.png
Here's how it looks in the lobby(just in bronze for now): https://i.imgur.com/6opF7cb.png

If there are any ideas on how to improve these so they'd be usable I'll happily implement those.

**Comment by ForbodingAngel** [comment]
The current rank icons are the same as the original ones. There were never complaints about the originals.

Additionally, the "blurryness" is from anti-aliasing due to resizing. This is unavoidable due to the fact that those icons will invariably be differently sized due to differing resolutions, etc.

Perhaps you should post a screenshot detailing how they look for you.

For me, they look like this: https://i.imgur.com/WzG1Jew.png

**Comment by DeinFreund** [comment]
And what about the possibility to display ELO as well as XP in just one icon? Or do you want to display the rating in some other way?

**Comment by ForbodingAngel** [comment]
The display of ELO is a separate issue, and not necessarily applicable, because that is very game specific. Not all games will be using ELO as a metric. Chobby is for spring in general. Not only ZK although it made sense to release for ZK first to hopefully quash as many bugs as possible, quickly.

**Comment by gajop** [comment]
Normally I think ranks should follow a few simple rules:
- The more items (like stripes), the higher the rank
- Bigger items are higher rank (big star vs small star)
- Different color can indicate rank, e.g. silver being higher than gold (or copper?)

I do not understand how Ranks 5-8 are designed but to me it's not clear at all which is a higher rank visually. Two will probably need to be removed.

Rank 4 is also a bit confusing, and Dein's version is a bit better because the two stripes aren't symmetric.

Colorwise (and elowise) I think I prefer not showing elo there, this makes it much simpler (and better looking), where elo could result in 20-50 different icons.

So my suggestion would be to rework 4-8, by altering 4, dropping two of 5-8 and introducing two new. It's also possible to have a silver version of 4 (new 5) and a gold version of 9(new 8), in order to add the missing values and make it more consistent.

**Comment by ForbodingAngel** [comment]
Imo, all of the ranks that have the ribbons and crap are confusing, but if you look at the originals, the ones I drew are exactly like the originals.

I welcome the opportunity to rework them altogether so that it makes more sense. Perhaps we should take a page from Blizzard Starcraft Ranks?

http://www.sc2mapster.com/media/images/83/199/Ranks.png

That said, don't get too enamored with those... They are displayed at 64x64 in battlenet and ingame, whereas what we have is displayed at about 16x16(ish), so we don't have a lot of detail to work with. The ones I made are good because they are colorful and easy to spot what they are. Where they fail is designating how one is better or worse than the other. That is a failing of the originals.

I made these now ones follow the originals because I didn't want to rock the boat, but it appears that the boat is in need of rocking. I'll do some work on these as soon as I can. :-)

**Comment by ForbodingAngel** [comment]
Maybe we should follow military rank insignia? I could remake these pretty easily (some variance would be needed):
https://m2.behance.net/rendition/pm/5800063/disp/6bd2ea07a54e39ef0270ad97ac340737.jpg

**Comment by gajop** [comment]
Change for the sake of change isn't acceptable, but here we have a clear case of things in need of improvement.
Looking at the military insignia (I'm going to completely ignore SC2 as I think that's awful):
- I like private->sergeant and general ones. It's very clear what the order is and I can imagine it not be too difficult to display (although perhaps we can limit to 3 star gens)
- Sgt major is spamming stripes (3+3), a 3+1 would've been OK, although even that might be too much. I like how top and bottom one is connected with a star.
- Major and Colonel ones are probably best to avoid
- Lieutenant and Captain ones are OK, but if we aren't doing color-based rank for anything else, I'd avoid it here too.

So imo, for 9 ranks:
[1,4]: Private -> Sgt. Major (Rework Sgt Major)
[5,6]: 1st LT and Captain 
[7,9]: 1 star -> 3 star general

Not sure about what colors to use, but even the army ones aren't bad, as it separates noob colors from experienced ones (once you're silver, you're basically not a newbie anymore).

**Comment by ForbodingAngel** [comment]
http://imgur.com/a/WXNje
https://i.imgur.com/lrW5YBu.png

**Comment by DeinFreund** [comment]
Definitely better than the current ones. I'd still like to see rating but I guess that's not gonna happen.

**Comment by ForbodingAngel** [comment]
Update on rank 9:
![Image of Ranks](https://i.imgur.com/ZxXT6lW.png)

**Comment by gajop** [comment]
It's worth keeping in mind that uber allocates only 3 bits for rank, allowing a total of 8 ranks.
Perhaps not important when designing, as that part of the protocol should really be changed.

**Comment by GoogleFrog** [comment]
Done, I think.
