### ISSUE TITLE
Rank level up notification

### ISSUE THREAD

**Issue by gajop** [Spring-Chobby/Chobby#238]
Make some sort of popup when player rises up a rank. 
"Congratulations, you have achieved the rank of ..."
- image (maybe with some animations/shaders)

**Comment by GoogleFrog** [comment]
Is this important? I feel like we need a coherent pavlovian design if we want to start working in that direction.

**Comment by ashdnazg** [comment]
I don't know if I'm the only one, but I hate the NightWatch PM in ZKL.

**Comment by ForbodingAngel** [comment]
Popup ranks are very important. This is because player progression is important to the player. It doesn't matter that the rank is essentially meaningless. We should have far more ranks than just 9, and a player should achieve those ranks reasonably quickly. Allowing for a crapload of ranks allows us to gently space the farther and farther apart until a player suddenly has 250 hours ingame and wonders where this beard came from and where his life went.

As a casual player, trust me. This sort of meaningless progression makes you feel good and fuels your desire to keep playing.

**Comment by gajop** [comment]
I agree with @ashdnazg , Nightwatch "level up" info is boring and annoying.
If there are hundreds of levels, I would rather use it for ranks (15~?) only for now, as an easy-to-dismiss, but stylish popup.

**Comment by ForbodingAngel** [comment]
Nightwatch no, but a popup with fanfare on ranking up _is_ important.

**Comment by gajop** [comment]
This is done now. May improve gfx/sound in the future as time allows it.
