### ISSUE TITLE
Hide matchmaker rooms

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-Chobby/Chobby#307]
Matchmaker rooms should be hidden from the battlelist. Hopefully they have some kind of status tag which says they are matchmaker rooms.

**Comment by Licho1** [comment]
No they should not. They should be visible to let non-invovled players join and watch. Also its important to show that people are active, what they are doing. Both to newcomers (who will be put off by empty lists) and to us.

Its fine to mark them clearly but hiding them would be disastrous.

**Comment by gajop** [comment]
Hiding them would be hardly disastrous. They're kinda confusing... What do they even mean? Why is everyone in a room with a confusing name "Matchmaker"?? Is that different from using the matchmaker?? <- Reasonable questions I can see newbies asking (as I was doing that just the other day).

If you wanna show a list of running games a user can spectate, all you need is just one button, titled "Spectate" sitting next to the name of the room. Otherwise it's not important.

Activity can be showed better in the status bar or next to each queue if you really want.

**Comment by Licho1** [comment]
Nah you want to see running games, not individual people. Im using it all that time, just looking at list of games in progress and join them to spec. 
You wont see most people, unless they are friends (thats the plan). You will see games though.

**Comment by GoogleFrog** [comment]
Nothing useful can occur from joining a MM battle room. No battle is going to occur in the future and the settings are fixed. Players should not be able to do actions with no purposes, it is confusing. MM battles may be spectated by clicking on the battle in the spectating submenu https://github.com/Spring-Chobby/Chobby/issues/308

All the rooms in the battlelist should function as rooms. MM battles should definitely not function as rooms.

**Comment by Licho1** [comment]
WHAT?? Did you seriously try to use it?
People DO join and they DO chat, they enter into those rooms even knowing battle cannot start there.
It's social thing and spectating. ZK has this awesome mid-game spectator join and thats what's it for, that's purpose. 
They also join there and chat with other people, including with players in debriefing, thats why it's best kept as a room because it is a room, only function that does not work is starting after game ends, but you should not assume this to be true for any of the rooms. 
If they do not enter room, but only spring game, they cannot interact fully with players in debriefing, which makes for a sad and lonly experience of the players. 

Ask people who actually use it like DeinFreund or hokomoko or me.

**Comment by GoogleFrog** [comment]
I think debrief should occur in the game itself. As far as I can tell there is no technical reason to not have debrief ingame. It makes the interface clearer to debrief in the game because the debriefing is the only purpose of the battleroom when usually battlerooms can do a lot more than debrief.

**Comment by Licho1** [comment]
There are technical reasons. It's expensive to keep dedicated server running, it's not as convenient to chat there and everything is so far tied to game exiting.
Until spring exits, there is no replay link, no infolog processing, no elo adjustment. 
You would want spring to be running until last person leaves? What if they go idle?

**Comment by ashdnazg** [comment]
Sane games have 2 independent lists, "Play" and "Watch". for some reason spring is still in the old  paradigm of putting them together.
having MM games in "Watch" makes sense, having them in "Play" doesn't.

**Comment by Licho1** [comment]
You are completely ignoring BENEFITS of having it together, features that other games don't have..
You can join room of running game, you can join ingame too and you can chat with people there..
This is a major social bonus that we have that other games don't. 
It would be a bad mistake to remove our advantage. 
It's also bad idea to hide running games out of sights. It works for huge games but we have handful of players and you will like to know where people are and what they are doing.

Imagine you want to play MP of some obscure odd game and see empty lists vs you see 5 running games ..
What gives better impression? What makes you more likely to just wait a bit?
