### ISSUE TITLE
"Problems with friend list" on uber

### ISSUE THREAD

**Issue by gajop** [Spring-Chobby/Chobby#495]
Details needed

**Comment by icexuick** [comment]
Well, f.e. i don't see friends in the list.
I'd like/expect to see my friends, both online and offline.
Also it's f.e. showing 7 players online, but none of them are displayed (probably bots).

**Comment by gajop** [comment]
> just tried friends with Bertje and thát worked!
> and next time i start, my friend is gone, but he is on server

**Comment by icexuick** [comment]
Yeah. So i can see him the first time, but later on i cannot.
And when i restart the game, he's also not there.
I'd also like an option to see/view the player/bots that are online - other wise the "online players" number feels a little odd.

**Comment by gajop** [comment]
Players and bots which are not your friends? That's out of scope of this issue.

Roger that on friends. I'll check if I can reproduce it.
Are there any other lobby clients that have working friend lists?

**Comment by icexuick** [comment]
Haha.

Well Springlobby works correct afaik.

**Comment by MasterBel2** [comment]
@gajop did you ascertain any more information about this issue? 

Bug description currently seems to be 
> Chobby doesn't remember friends

Is this correct? Either way can the original ticket be `edit`ed with the correct bug description?

**Comment by gajop** [comment]
Chobby isn't supposed to remember friends. This is what the lobby server does. It should give you a list of friends, of both offline and online users, and Chobby should display both.

**Comment by MasterBel2** [comment]
> Chobby isn't supposed to remember friends. This is what the lobby server does.
I see how it wasn't clear that this was what I was meaning.

I've encountered the issue that seems to be described. Steps taken to produce:

1. Bring 2 accounts online that are not friends with each other. One on custom lobby without friends implemented. One on Chobby.
2. Chobby account sends a request to the account logged in on the custom lobby.
3. Both accounts log off.
4. Account that was signed in on custom lobby logs in on Chobby.
5. Friend request is present, and is accepted. The request panel is replaced with a friend panel.
6. Close Chobby.
7. Open Chobby and connect with the account that just accepted the friend request.
8. Chobby does not show the friend as present.

Currently getting rossco to look into this for the BAR server. Edit: Server has the correct data in the database.
Will now dig into Chobby because the error seems to be there.

**Comment by MasterBel2** [comment]
Well this seems to be the problem:
`lua
function Lobby:_OnFriendList()
	self:_CallListeners("OnFriendList", self:GetFriends())
end
`

**Comment by MasterBel2** [comment]
Yep. 
![image](https://user-images.githubusercontent.com/39206414/87120424-b340c880-c2c3-11ea-8b08-42d4343b52a2.png)

**Comment by MasterBel2** [comment]
@gajop I believe this can be closed now.

**Comment by gajop** [comment]
@MasterBel2 Indeed. In future feel free to close the issue by writing "close https://github.com/Spring-Chobby/Chobby/pull/514" (I recommend using the full URL so it doesn't cause issue to ZK fork)
